language: php

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.testing .env
  - php artisan serve &
  - php artisan dusk