sudo: required
language: php
dist: trusty

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

php:
  - 7.1

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &
  - php artisan dusk

notifications:
  email:
    on_success: never
    on_failure: never