sudo: required
language: php
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - chmod -R 0755 vendor/laravel/dusk/bin
  - php artisan serve &
  - sleep 3

script:
  - php artisan dusk

notifications:
  email:
    on_success: never
    on_failure: never