sudo: required
language: php
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

php:
  - 7.1

before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - chmod -R 0755 vendor/laravel/dusk/bin
  - php artisan serve &
  - sleep 5

script:
  - php artisan dusk

notifications:
  email:
    on_success: never
    on_failure: never