sudo: required
language: php
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

php:
  - 7.1

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start &
 - sleep 5

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - php artisan serve &
  - sleep 5

script:
  - php artisan dusk

notifications:
  email:
    on_success: never
    on_failure: never