sudo: required
language: php
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

php:
  - 7.1

before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - chmod -R 0755 vendor/laravel/dusk/bin
  - php artisan serve &
  - sleep 3

script:
  - php artisan dusk

notifications:
  email:
    on_success: never
    on_failure: never