sudo: required
language: php
dist: trusty

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - export APP_ENV="testing"

script:
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
#  - cp .env.dusk.testing .env
  - php artisan serve &
  - php artisan dusk

after_failure:
  - curl http://127.0.0.1:8000

notifications:
  email:
    on_success: never
    on_failure: never